### ISSUE TITLE
Lack of assist support when using session properties with SqlAlchemy

### ISSUE THREAD

**Issue by jamiedavenport** [cloudera/hue#1057]
## Problem

Following on from #1048 we are now prompted for a username and password which are used to complete a parameterised URL. However, we are still lacking assist support since session data is obtained via the `notebook` object passed into `execute` which is not present during calls to `autocomplete`.

We've worked around this issue by implementing the same approach as the JDBC connector ([Code Here](https://github.com/jamiedavenport/hue/blob/sqlalchemy-session-assist-support/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py)):
* Add a global in-memory `API_CACHE`
* Implement the `create_session` method which creates and stores an engine object in the cache
* Retrieve the engine in calls to `autocomplete`

This has some shortcomings such as:
* The cache size is unbounded
* Users may need to enter their credentials multiple times
* Doesn't allow different cache strategies or stores

## Proposed Solution

Abstract the idea of a `SessionStore` which can easily be extended with multiple backend to give admins control over session handling. Example Implementations:
* In-Memory Cache (What the JDBC already does)
* DynamoDB Store where admins would have control over the TTL and encryption
* `create_session` and `close_session` methods can simply refer to this store

**Comment by romainr** [comment]
Nice description. I see two main things. Persistence of:

1. credentials optionally typed by the end user (mainly about this issue)
2. sqlalchemy session objects (could be split in another issue)

Generally we should remove this global cache variable. A bit similar to #1020. Django also has a pluggable cache system that can TTL keys: https://github.com/cloudera/hue/blob/master/desktop/libs/libsentry/src/libsentry/privilege_checker.py#L23

About 1., another possibility would be to persist it in the browser (that was the original idea), so that there is no need to deal with the tricky security of handling end user credentials in the backend. This would also scale elegantly. Those credentials would automatically picked-up by create_session (https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/apps/notebook/notebook.js#L368) and added to the request data if they are there so that the backend API create_session get them and persist them in Django' cache system with a TTL.

e.g. Frontend with totalStorage() and 'showAuthModal' https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/ko/components/ko.sessionAuthModal.js
@JohanAhlen 

About 2.,
For actual connections/SqlAlchemy session object, building a pool of them similarly to the Thrift for the HiveServer interface (https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/thrift_util.py and https://github.com/cloudera/hue/tree/master/apps/beeswax/src/beeswax/server). Note that SqlAlchemy pools are url based so it would be one pool per user it seems: https://docs.sqlalchemy.org/en/13/core/pooling.html

IIRC correctly, one issue with non in API server memory was that the Python objects could not be pickled and stored there (or need to investigate something like Dill https://github.com/uqfoundation/dill). 

Long term is to move to the Celery Task Server which also needs a store like Redis. 

- Task Server workers http://issues.cloudera.org/browse/HUE-8738
- Result caching and storage http://issues.cloudera.org/browse/HUE-8787

**Comment by jamiedavenport** [comment]
Let's split 2 out into another issue since it's more of an optimisation for the SQLAlchemy connector.

Storing the credentials in the browser would work but we run Hue in a remote environment where users connect to and when finished their session is destroyed. So the user would have to enter their credentials each time. We would also have to encrypt the data before storing it to prevent those credentials being discovered if the device is compromised.

Using a server-side store such as Dynamo would be convenient for this but I realise this is probably an edge-case. I don't think Hue would need to be responsible for handling the credentials securely if the operators ensure proper encryption-in-transit and encryption-at-rest.

I wonder if there's room for both cases:
1. Look for credentials passed from the client-side
2. Otherwise fallback to a configured session store

**Comment by JohanAhlen** [comment]
For the credentials, Local Storage and IndexedDB are not considered safe, we'd indeed need to encrypt ourselves which seems messy.

A better option could be the Credential Management API, https://w3c.github.io/webappsec-credential-management/ I'll take a spin at it and see if I can come up with something in ko.sessionAuthModal.

**Comment by romainr** [comment]
Both could live, but for sure management password is often the last thing the service should do :)

Curious if we could leverage the Chrome password manager on the frontend too? (similar to traditional website logins). That might be even simpler and secure.

**Comment by jamiedavenport** [comment]
We should be cautious of compatibility between different browsers and older versions. Solving this on the backend would solve these issues and be more secure (since Hue is not responsible for encryption which is left to the session store).

We could expose multiple options for the session store to allow admins to choose what's best for them:
- InMemory to ensure credentials are never persisted
- Dynamo or DB for when user convenience is important

Alternatively, we could modify the API so that session properties are sent with each request. The properties could be kept in-memory on the client-side, this would fix the issue but not provide any convenience for the user and would be a large change.

**Comment by romainr** [comment]
Yes, both options have pros and cons. 

> Alternatively, we could modify the API so that session properties are sent with each request. The properties could be kept in-memory on the client-side, this would fix the issue but not provide any convenience for the user and would be a large change.

Yes, that's how it was designed 4 years ago. It is not much change as only for the create_session call but there is no persistence.

Feel free to have a stab at the backend one. Especially as there will be a redis soon it might be convenient. Django Cache probably supports DynamoDB has backend too.

We will probably iterate on the client side only solution too.
