### ISSUE TITLE
Oozie job browser's graph do not show red/green bars for failed/successful subworkflows

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1272]
Describe the bug:

While testing a failed coordinator run with the new Hue version I noticed that the Oozie's Job browser graph doesn't show anymore red/green bars under the subworkflows failed/completed. It is more difficult to find what was the problem and debug it under this conditions :(

To visualize:

**Current behavior**:
![Screen Shot 2020-09-22 at 8 44 04 AM](https://user-images.githubusercontent.com/1536240/93851194-fe0d9200-fcaf-11ea-90f8-8dc16343bbab.png)

-------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------

**Expected/old behavior**:
![Screen Shot 2020-09-22 at 8 44 56 AM](https://user-images.githubusercontent.com/1536240/93851212-01088280-fcb0-11ea-95d9-8587dd3ca997.png)

I noticed the following JS error though:

```
hue.errorcatcher.34bb8f5ecd32.js:31 Hue detected a Javascript error:  https://hue-next.wikimedia.org/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-4d9d2c608a19e4e1ab7a.51951e55bebc.js 1705 2 Uncaught Error: Syntax error, unrecognized expression: [id^=wdg_@add_partition]
window.onerror @ hue.errorcatcher.34bb8f5ecd32.js:31
jquery.js:1677 Uncaught Error: Syntax error, unrecognized expression: [id^=wdg_@add_partition]
    at Function.Sizzle.error (jquery.js:1677)
    at Sizzle.tokenize (jquery.js:2377)
    at Sizzle.select (jquery.js:2838)
    at Function.Sizzle [as find] (jquery.js:894)
    at jQuery.fn.init.find (jquery.js:3095)
    at new jQuery.fn.init (jquery.js:3205)
    at jQuery (jquery.js:157)
    at <anonymous>:66:25
    at Object.D (knockout-latest.js:11)
    at Object.success (<anonymous>:59:26)
    at fire (jquery.js:3496)
    at Object.fireWith [as resolveWith] (jquery.js:3626)
    at done (jquery.js:9786)
    at XMLHttpRequest.<anonymous> (jquery.js:10047)
```

Steps to reproduce it?

Simply navigate to an URL like `/hue/jobbrowser/jobs/0009826-200915132022208-oozie-oozi-W#!id=0009824-200915132022208-oozie-oozi-W`.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

4.7.1

**Comment by elukey** [comment]
@romainr any idea?

**Comment by milimetric** [comment]
We just need to escape special characters here, as per jQuery guidelines "To use any of the meta-characters ( such as  !"#$%&'()*+,./:;<=>?@[\]^`{|}~ ) as a literal part of a name, [it must be escaped with with two backslashes: \\](https://api.jquery.com/category/selectors/)".  I'll send a PR escaping these.

**Comment by romainr** [comment]
In case it helps, template filters might even be there and IIRC something similar was already done in the oozie templates somewhere

`from django.template.defaultfilters import escape, escapejs`
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/templates/common_header_footer_components.mako#L18

https://github.com/cloudera/hue/blob/master/apps/oozie/src/oozie/templates/editor/coordinator_properties.mako#L70

**Comment by milimetric** [comment]
Ah, cool, thx, I'm testing a version with simply `$.escapeSelector` which is built into jquery, but I see the example on `coordinator_properties` does indeed do something similar.  Let me know if you have preferences, I can submit it this way and yall can decide later too.

**Comment by milimetric** [comment]
Ok, it looks like using `$.escapeSelector` [here](https://github.com/milimetric/hue/blob/master/apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow.mako#L679) and [here](https://github.com/milimetric/hue/blob/master/apps/oozie/src/oozie/templates/dashboard/list_oozie_workflow_graph.mako#L91) fixes the selector error and allows that code to complete, but some HTTP 500 errors showed up.  The subworkflow links throw errors as well, and it looks like they're still missing bars.  I can still submit the PR if it helps someone else investigate, but it doesn't seem to solve the issue.

**Comment by elukey** [comment]
The 500 looks like:

```
[24/Sep/2020 17:51:07 +0000] navigator_client INFO     {"query": "((originalName:**^3)OR(originalDescription:**^1)OR(name:**^10)OR(description:**^3)OR(tags:**^5))AND((originalName:[* TO *])OR(originalDescription:[* TO *])OR(name:[* TO *])OR(description:[* TO *])OR(tags:[* TO *]))", "facetFields": ["tags"], "filterQueries": ["deleted:false"]}
[24/Sep/2020 17:51:07 +0000] navigator_client ERROR    Failed to search for entities with search query: {"query": "((originalName:**^3)OR(originalDescription:**^1)OR(name:**^10)OR(description:**^3)OR(tags:**^5))AND((originalName:[* TO *])OR(originalDescription:[* TO *])OR(name:[* TO *])OR(description:[* TO *])OR(tags:[* TO *]))", "facetFields": ["tags"], "filterQueries": ["deleted:false"]}
[24/Sep/2020 17:51:07 +0000] access       INFO     XX.XX.XX, 10.20.0.54, 10.64.21.128 elukey - "POST /metadata/api/catalog/list_tags HTTP/1.1" returned in 4ms 500 307
```

**Comment by elukey** [comment]
Created also https://github.com/cloudera/hue/issues/1273 for another issue, that may or may not be related..

**Comment by milimetric** [comment]
@romainr some thoughts on the problem and potential ways forward:

After some more debugging, I found a mismatch between element ids rendered to the page by python and string transformations on api data in JS.  I fix one of the places where this is a problem via https://github.com/milimetric/hue/commit/0e3eec447cef56b4825f8d2896597d24c03f1a92#diff-16573ed4215a23c201e61abcca6e4ec68c00e96956fdae65cfa0dc11042ef1f0L85, but I feel like the issue is more general and would not want to contribute a partial fix.

Basically, this kind of coordination between html and api-returned data should be hardened against possible string manipulation bugs and other mismatches.  For example, on line https://github.com/milimetric/hue/commit/641840bd46350ea700915657c93703aced78ee23#diff-16573ed4215a23c201e61abcca6e4ec68c00e96956fdae65cfa0dc11042ef1f0R90 there's a gotcha if you don't notice that the `substr` returning `-1` is planned-for via the +1.  If someone moves that code around they may miss that gotcha and re-introduce a bug.  Since strings can evolve in unpredictable ways with new features, etc, it's entirely possible that a valid jquery selector can be created via an invalid string transformation.  In on-click handlers this is not such a big deal and can be fixed by fixes like mine above, but in operations that kill, rerun, etc. jobs this could have a much more negative impact.

There are a few best practices ways of doing this, but they require large changes in the code:

* Render html only in JS, do not coordinate with a server-side renderer.  This would allow migration of any id-matching code to move into data-manipulation code, especially with a framework like knockout.
* If you do require server-side rendering, use server-side rendering best practices, as can be seen with Vue's SSR or other solutions people have built around knockout or any framework you'd like to use.
* If you must coordinate python-rendered code with JS, consider sharing the same exact data model so that the match is identical.  In other words, you should be able to directly do `$(\`#${actionId}\`)` without any string manipulation.

I'd be happy to advise further or have a quick call with the relevant team (on a volunteer basis, of course, I like my day job :))

**Comment by romainr** [comment]
Yes, this part of Hue is very old and not on part at all with best engineering practices.

Proper components with vuejs have been kickstarted recently https://docs.gethue.com/developer/components/er-diagram/ and starting with the editor and popular widgets lile File Chooser/Inputs etc.. will be gradually ported and improved.

Feel free to send your PR! With regards to the Oozie App we are focusing more right now on the Editor and first order components.

**Comment by elukey** [comment]
@romainr any chance that you could file the PR? :)

**Comment by elukey** [comment]
@romainr is https://github.com/milimetric/hue/commit/641840bd46350ea700915657c93703aced78ee23 something that we can consider to commit to bypass some current viz issue?

**Comment by romainr** [comment]
This is open to the community. A clean rewrite as a component or little fix case by case are fine. Best best is to move all the rendering logic to the UI but this is much more work so case by case is good for now.

We will look at having SQL query scheduling by end of 2020 or Q1 2021 but that might or might not help for the Oozie piece.

**Comment by elukey** [comment]
@romainr yep I understand, but what I meant is what is upstream plan since there are a number of features that are a bit broken, and that were not on previous versions of Hue (like the ones that we currently are migrating from, the one contained on CDH 5.16). I see those as clear regressions from something that was working :)

**Comment by romainr** [comment]
Cf. above the focus is currently on the Query Editor v2 for the medium term as there is a lot to improve there and there is unfortunately limited resources :) When the Query Scheduling will be tackled it will be a better time.

**Comment by elukey** [comment]
@romainr I agree 100% that resources are limited and that you'd prefer to concentrate on new features, what we are wondering at the moment is if https://github.com/milimetric/hue/commit/641840bd46350ea700915657c93703aced78ee23 is fine in your opinion (since you have a lot more context than us about the codebase) or not. The code change also fixes #1273, we have it applied on our debian package and it looks good, but without having the full context on the codebase and future plans it is difficult to understand what to do. "This is open to the community" is great to see but upstream should weight in with some suggestion, otherwise we may keep patching the wrong things.

As you have seen during the past months we are very open to send patches and contribute to the project, even if the last releases are more experimental than ready to prime time for production, but some guidance from you would be great :)

**Comment by romainr** [comment]
I would recommend small iterative patches like above for the current time for this part of Hue, this would be the best ROI.

Any improvement is warmly welcomed :)

**Comment by elukey** [comment]
Still need to be fixed :)

**Comment by elukey** [comment]
This is still a bug!

**Comment by elukey** [comment]
Still a bug :)

**Comment by milimetric** [comment]
Still a bug
