### ISSUE TITLE
Unable to switch Chinese

### ISSUE THREAD

**Issue by qq712679031** [cloudera/hue#1546]
I have modified the hue-release-4.8.0/desktop/core/src/desktop/settings.py 

LANGUAGE_CODE = 'zh-CN'

LANGUAGES = [
  ('de', _('German')),
  ('en-us', _('English')),
  ('es', _('Spanish')),
  ('fr', _('French')),
  ('ja', _('Japanese')),
  ('ko', _('Korean')),
  ('pt', _('Portuguese')),
  ('pt_BR', _('Brazilian Portuguese')),
  ('zh-CN', _('Simplified Chinese')),
]

make apps  But it didn't work out

**Comment by romainr** [comment]
https://docs.gethue.com/user/concept/#changing-the-language

and more explanation on the logic via https://github.com/cloudera/hue/pull/1592

**Comment by victorvli** [comment]
Although I finally switch hue to Chinese through many efforts, I still have some questions.
1. Is it nesessary to **change the value of 'LANGUAGE_CODE' to 'zh-CN'** in desktop/core/src/desktop/settings.py since I can change language preference in 'My Profile' page through web ui?
2. Is it nesessary to **run "make locales"**? If yes, does this operation have causal relationship with operation 1?
3. I've changed language preference to "simplified chinese" and update user. But if I open a private window or change another browser, the language preference is **still "english" or even "german"**. Is the setting persisted?
