### ISSUE TITLE
Special characters not handled by the HDFS file browser

### ISSUE THREAD

**Issue by chtefi** [cloudera/hue#296]
Hello,

It seems Hue can't access folders composed of special characters such as ":" (in my case, it's in the name of some Impala partitions).

They are allowed by HDFS (using the % notation) :
```
$ hdfs dfs -mkdir /tmp/toto%3Ahello
$ hdfs dfs -ls -d /tmp/toto%3Ahello
drwxr-xr-x   - me supergroup          0 2016-01-14 17:58 /tmp/toto%3Ahello
```
If you try to access it via Hue's file browser (while logged as "hdfs"), you get an error :
```
Cannot access: /tmp/toto:hello. Note: You are a Hue admin but not a HDFS superuser (which is "hdfs").
```

Stéphane

**Comment by romainr** [comment]
@spaztic1215 we are good now I think?

**Comment by spaztic1215** [comment]
@chtefi Unfortunately, the issue is that Impala shouldn’t be escaping these invalid HDFS special characters in the first place, it should just reject invalid HDFS characters. Hue's default behavior is to decode URI-escaped characters b/c there are cases where unicode chars (like in Pyrénées) are valid in HDFS but need to be URI-encoded (pyr%C3%A9n%C3%A9es) by the Hue filebrowser.

It would be good to file an issue with Impala though, so that these invalid chars are not auto-escaped: https://issues.cloudera.org/projects/IMPALA
