### ISSUE TITLE
Hue version on docker image

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#344]
What version of Hue is on docker image (gethue/hue:latest from docker hub) ? Is it 3.9 ?

Thanks!

**Comment by romainr** [comment]
It pulls directly from the github, so the very latest on master

**Comment by JMetai** [comment]
Thanks!

**Comment by nsteinmetz** [comment]
Hi,

Hue image is reported as pushed 5 months ago ; so I don't think it pulls directly from github and it does not seem to be an automated build too.

I tried to build it from scratch and it fails when compiling some botoo dependencies. Trying to build a 3.9 release instead of master in the meantime as it worked some months ago.

Nicolas

**Comment by romainr** [comment]
The plan is to re-update this one in 1 month when Hue 3.10 is out! @enricoberti
