### ISSUE TITLE
Cannot modify hive.server2.logging.operation.verbose 

### ISSUE THREAD

**Issue by wgzhao** [cloudera/hue#374]
I use Hue release 3.10.0 with Hortonworks HDP 2.4. 
When I click  `Notebooks` menu . it show a popup window with a error message : `Failed to open new session: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot modify hive.server2.logging.operation.verbose at runtime. It is not in list of params that are allowed to be modified at runtime`

I try modify the line 573 in  `apps/beeswax/src/beeswax/server/hive_server2_lib.py` 
change 
`kwargs['configuration'].update({'hive.server2.logging.operation.verbose': 'true'}`
to
`kwargs['configuration'].update({'hive.server2.logging.operation.verbose': 'false'}`

It works!

**Comment by spaztic1215** [comment]
We should probably remove the hive.server2.logging.operation.verbose configuration since it's actually not  a config that can be modified at runtime or on opening a session. It is read by HS2 at service init time only. This is because it must create a new Log4j appender object to capture the logs and the verbosity config dictates the PatternLayout as well as the filters to apply to the loggers.

**Comment by spaztic1215** [comment]
Removed these ignored properties as of https://github.com/cloudera/hue/commit/afd5c5a9f438961d61268ac83d904af6e838295f
