### ISSUE TITLE
Deactivate all data dowloads

### ISSUE THREAD

**Issue by YannBrrd** [cloudera/hue#611]
Hello,

Is there a way to deactivate all data downloads in Hue ? 

Thanks.

Regards,
Yann

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-7414

**Comment by KevinLefevre** [comment]
Meanwhile the issue is been resolved, I propose this workaround:
In the file desktop/core/src/desktop/templates/common_notebook_ko_components.mako you can comment the download section, and restart your instance, the download button will no longer appear or be available. The section incriminated is <%def name="downloadSnippetResults()">
For the HDFS downloads, it is possible by configuration in the conf file hue.ini.

Note that none of these currently supports habilitations. Once deactivated, no one can download data anymore.
