### ISSUE TITLE
Intellisense (Autocomplete) doesn't show if there is text below

### ISSUE THREAD

**Issue by guidooswald** [cloudera/hue#755]
Impala SQL Editor, Hue 4.1:
If you start in the line above existing code (no semicolon at the end, yet), Intellisense will not show (CTRL-Shift not working).

**Comment by JohanAhlen** [comment]
Generally this should work, however there are some cases when Hue won't be able to find any suggestions. It could be caused by open parentheses or too many syntax errors in the statement. The semicolon is important but mostly for the second statement.

Would it be possible to share the queries? Obfuscated would be fine.

Also, to trigger the autocomplete use CTRL/CMD - space. To be sure, you can also check if the autocomplete is enabled or not (CTRL/CMD - ,)
