### ISSUE TITLE
'Table Browser' for mysql from snippet doesn't work

### ISSUE THREAD

**Issue by nomoo** [cloudera/hue#763]
Hello, i've tried both 4.2 and 4.3 releases. I set up two sources: hive and mysql: hive table browser is working fine and mysql table browser works only if i go to 
`'menu' > 'browsers' > 'tables' > 'mysql'`

If i try to open 'table browser' from left column: 

`'SQL' > 'Sources' > 'mysql' > 'test_database' > 'test_table' > .press 'info' > 'Table Browser'`
i get:
>    DB Error
>
>Error while compiling statement: FAILED: SemanticException [Error 10001]: Table not found test_database.test_table

AFAIU hue tries to search it in hive.

**Comment by whitelez** [comment]
I am facing the same in both 4.2 and 4.3
Have you found out any solution?

**Comment by nomoo** [comment]
> I am facing the same in both 4.2 and 4.3
> Have you found out any solution?

Nope, I hope devs will fix that in next release.

**Comment by davidkim83** [comment]
This is my very first Github comment, so please bear with me if there's anything unfamiliar.

So here's what I have:
- CentOS 7
- MariaDB 10.2.2
- HDP 3.1 (for testing)
- Hue 4.3

Hue gave me a debug log like below: (here, **오류** means **Error**)

`[05/Mar/2019 00:03:14 +0900] middleware   INFO     Processing exception: DB 오류: Traceback (most recent call last):
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/hue/apps/metastore/src/metastore/views.py", line 288, in describe_table
    raise PopupException(_("DB Error"), detail=e.message if hasattr(e, 'message') and e.message else e)
PopupException: DB \uc624\ub958
[05/Mar/2019 00:03:14 +0900] thrift_util  DEBUG    Thrift call: <class 'TCLIService.TCLIService.Client'>.ExecuteStatement(args=(TExecuteStatementReq(confOverlay={}, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(secret=d34f5f461e0732ac:ff33d64ac7f5f2a0, guid=1d49fcfa9706b3b3:9b5a6903bf4d4b2)), runAsync=False, statement='DESCRIBE FORMATTED `druid`.`druid_audit`'),), kwargs={})
`

I'm thinking the statement DESCRIBE FORMATTED might not be applicable to MySQL/MariaDB.
It works for Hive well and good.
Perhaps it's a configuration error, but since it was raised from 
- file : /usr/local/hue/apps/beeswax/src/beeswax/server/dbms.py
- line : 232
- function : get_table
, I think it's trying to describe a MySQL table as if it was a Hive table.

Any suggestions? Maybe a mis-config?

**Comment by jdesjean** [comment]
@davidkim83 That's a good assumption, it looks like it's accessing the MySQL table using Thrift. Can you give more information on how you configured MySQL in Hue?

**Comment by davidkim83** [comment]
Hi, sorry for the late reply.
Here's my hue.ini file, sanitized to mask hosts and passwords, and removed all comments for brevity.
[hue.ini.txt](https://github.com/cloudera/hue/files/2936494/hue.ini.txt)

As for MySQL (MariaDB), I have:
- MariaDB Server 10.2.21 for CentOS 7.6 (installed from official repo recently)
- mysql client Ver 15.1 Distrib 10.2.21-MariaDB using readline 5.1
- in /etc/my.cnf, i moved `datadir`, `tmpdir`, `socket` to another location for the server and have set `lower_case_table_names=1`
- in /etc/my.cnf.d/server.cnf, I have `character-set-server=utf8` for [mysqld]
- `printenv` gives `LANG=ko_KR.UTF-8`, the reason I matched mysqld character set
- I have nothing configured in neither /etc/my.cnf.d/client.cnf nor mysql-clients.cnf
- in /etc/profile.d/jdbc.sh, I set the `CLASSPATH` variable to include JDBC jars in `/usr/share/java` - they include the full file names, separated with :

Would these help in any way?
Do you know if there is anything else I should try?

**Comment by jdesjean** [comment]
@davidkim83, it's same issue as the other posters. The left assist & the editor work correctly with all configured databases, but the table browser currently only works with Hive & Impala.
