### ISSUE TITLE
spark-sql support for hue notebook

### ISSUE THREAD

**Issue by bgajjela** [cloudera/hue#810]
Hello,

Do we have any roadmap for below feature ?

https://issues.cloudera.org/browse/LIVY-19

Thanks,
Bharath

**Comment by romainr** [comment]
Seems like it is available now in Livy 0.5: https://livy.incubator.apache.org/docs/latest/rest-api.html

Does it work if you add this in the hue.ini?
```
[notebook]
  [[interpreters]]
    [[[sparksql]]]
      name=SparkSql
      interface=livy
```

**Comment by IVitamin-C** [comment]
It works, but does not support bulk queries

**Comment by bgajjela** [comment]
Liu,

Thanks for the confirmation . Can you please explain more about bulk queries ?

Thanks,
Bharath

**Comment by IVitamin-C** [comment]
I'm sorry I gave you the wrong answer and it has been deleted, I now use spark - SQL through 'org. Apache. Spark. SQL. Hive. Thriftserver. HiveThriftServer2'.
We also tried 'interface=sqlalchemy' (it doesn't seem to support multi-row queries).
If you need to run spark SQL using livy, you do
[notebook]
  [[interpreters]]
    [[[sql]]]
      name=Sql
      interface=livy
You also need to keep the [sparksql] parameter alive, otherwise you will get an error.
so 
[[[sparksql]]]
      name=SparkSql
      interface=hiveserver2

    [[[sql]]]
      name=sql
      interface=livy
but  
But there was a mistake
Livy -session will appear repeatedly, but the result cannot be displayed. It seems that there is no resource to run.
@romainr 
![image](https://user-images.githubusercontent.com/35019926/56460307-5497e200-63d3-11e9-9851-747bba0523cb.png)
![image](https://user-images.githubusercontent.com/35019926/56460308-5bbef000-63d3-11e9-9cba-860dcf246d3a.png)
And  it ran successfully and I can't stop it

**Comment by romainr** [comment]
https://review.cloudera.org/r/13934/ will make it work with Sql.

Re-suing the existing sessions will come in another jira.
