### ISSUE TITLE
Using tarball needs make apps again

### ISSUE THREAD

**Issue by sandredd** [cloudera/hue#949]
we have hue compiled using make apps and it works good. When I use make prod to create tar ball for prod release it creates tar without binaries and I have to compile again using make apps. 
Is there a way to create tar ball ship to new server and then start service without have to compile again . 
Ps: both build and prod servers are on same arch, os etc..

**Comment by romainr** [comment]
If it is exactly the same, does a simple copy work?

I know the CDH packaging is using too:
https://github.com/cloudera/hue/blob/master/tools/relocatable.sh

Note: hopefully we can get rid of this second stage of compilation in https://issues.cloudera.org/browse/HUE-8737 by switching to use pip install of the module dependencies instead of compiling them all.

**Comment by sandeepreddy3647** [comment]
Thanks @romainr 
Direct copy works but we want to build and deploy using jenkins pipeline in production. May be i'll try to update jenkins with same steps.
